In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
from sympy import sympify 



class TwoBodyOperator: 
    def __init__(self, nstates):
        """
        Constructor
        Args: 
            nstates    int
                the number of possible states
                given our truncation in the 
                basis set. 
        """
        self.maximal_index = nstates-1
        self.Vmat = np.zeros((nstates, nstates, nstates, nstates))
        
    def get_values(self, df): 
        """
        Args: 
            df pd.DataFrame
                updates self.VMat elements 
        """
        for i in range(len(df["V"])): 
            p = df["p"][i]-1
            q = df["q"][i]-1
            r = df["r"][i]-1
            s = df["s"][i]-1
            self.Vmat[p, q, r, s] = float(sympify(df["V"][i]))
        return self.Vmat 
        
        
        
    def value(self, element_indices): 
        """
        Args: 
            element_indices list of ints, length 4
                Indices for value of matrix 
                we want. 
                
        Returns: 
            Wanted matrix element
        """
        
        
        """
        for element in element_indices: 
            if element > self.maximal_index: 
                msg = 'index out of bounds'
                raise ValueError(msg)
            if not isinstance(element, int): 
                msg = 'Indices need to be ints'
                raise TypeError(msg)
        """
        #self.VMat[element_indices[0], element_indices[1], element_indices[2], element_indices[3]]
        return self.VMat[element_indices[0], element_indices[1], element_indices[2], element_indices[3]]
    
    def value_AS(self, element_indices): 
        """
        Args: 
            element_indices list of ints, length 4
                Indices for value of matrix 
                we want. 
                
        Returns: 
            Wanted matrix element antisymmetrized
        """
        return self.VMat[element_indices[0], element_indices[1], element_indices[2], element_indices[3]]\
                -self.VMat[element_indices[0], element_indices[1], element_indices[3], element_indices[2]]
    

    
    
    
    
    
    
        
        
        

In [2]:
path= "/home/jeb/Documents/Physics/FYS4480/Exercises/Midterm"

V = pd.read_csv(path+"/V.csv")

V

p  q  r  s                                       V
0   1  1  1  1                                 (5*Z)/8
1   1  1  1  2                  (4096*Sqrt[2]*Z)/64827
2   1  1  1  3                 (1269*Sqrt[3]*Z)/50000 
3   1  1  2  1                  (4096*Sqrt[2]*Z)/64827
4   1  1  2  2                              (16*Z)/729
.. .. .. .. ..                                     ...
76  3  3  2  2                       (73008*Z)/9765625
77  3  3  2  3  (6890942464*Sqrt[2/3]*Z)/1210689028125
78  3  3  3  1                (617*Z)/(314928*Sqrt[3])
79  3  3  3  2  (6890942464*Sqrt[2/3]*Z)/1210689028125
80  3  3  3  3                              (17*Z)/256

[81 rows x 5 columns]

In [3]:
VV = V["V"].copy()
VNew = V.copy() 
for i in range(81): 
    VV[i] = VV[i].replace("Z", "2")
    VV[i] = VV[i].replace("Sqrt[","sqrt(")
    VV[i] = VV[i].replace("]", ")")

for i in range(81): 
    VNew["V"][i] = VV[i]
    
VHe = VNew 

VVV = V["V"]
VBe = V.copy() 
for i in range(81): 
    VVV[i] = VVV[i].replace("Z", "4")
    VVV[i] = VVV[i].replace("Sqrt[","sqrt(")
    VVV[i] = VVV[i].replace("]", ")")

for i in range(81): 
    VBe["V"][i] = VVV[i]
    
VBe

/tmp/ipykernel_15572/2150207513.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  VNew["V"][i] = VV[i]
/tmp/ipykernel_15572/2150207513.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  VVV[i] = VVV[i].replace("Z", "4")
/tmp/ipykernel_15572/2150207513.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  VVV[i] = VVV[i].replace("Sqrt[","sqrt(")
/tmp/ipykernel_15572/2150207513.py:18: SettingWithCopyWarning: 
A value is trying to be s

p  q  r  s                                       V
0   1  1  1  1                                 (5*4)/8
1   1  1  1  2                  (4096*sqrt(2)*4)/64827
2   1  1  1  3                 (1269*sqrt(3)*4)/50000 
3   1  1  2  1                  (4096*sqrt(2)*4)/64827
4   1  1  2  2                              (16*4)/729
.. .. .. .. ..                                     ...
76  3  3  2  2                       (73008*4)/9765625
77  3  3  2  3  (6890942464*sqrt(2/3)*4)/1210689028125
78  3  3  3  1                (617*4)/(314928*sqrt(3))
79  3  3  3  2  (6890942464*sqrt(2/3)*4)/1210689028125
80  3  3  3  3                              (17*4)/256

[81 rows x 5 columns]

In [4]:
VBe

p  q  r  s                                       V
0   1  1  1  1                                 (5*4)/8
1   1  1  1  2                  (4096*sqrt(2)*4)/64827
2   1  1  1  3                 (1269*sqrt(3)*4)/50000 
3   1  1  2  1                  (4096*sqrt(2)*4)/64827
4   1  1  2  2                              (16*4)/729
.. .. .. .. ..                                     ...
76  3  3  2  2                       (73008*4)/9765625
77  3  3  2  3  (6890942464*sqrt(2/3)*4)/1210689028125
78  3  3  3  1                (617*4)/(314928*sqrt(3))
79  3  3  3  2  (6890942464*sqrt(2/3)*4)/1210689028125
80  3  3  3  3                              (17*4)/256

[81 rows x 5 columns]

In [5]:
TwoBody = TwoBodyOperator(3)
VHe = TwoBody.get_values(VHe)
VBe = TwoBody.get_values(VBe)

In [6]:
states = np.zeros(shape=(6, 6), dtype=bool)
for i in range(6): 
    states[i,i] = True
states[0, 1] = True; states[1, 0] = True; states[2,1]=True
states[3, 0] = True; states[4, 1] = True; states[5, 0] = True
sp_energies = np.zeros(6)
sp_energies[0] = -2; sp_energies[1] = -2; sp_energies[2] = -0.5
sp_energies[3] = -0.5; sp_energies[4] = -2/9; sp_energies[5] = -2/9


ketstates = states
brastates = states.T


In [7]:
class Hamiltonian: 
    def __init__(self, Z, states, V): 
        self.Z = Z
        self.brastates = states
        self.ketstates = states.T
        self.V = V 
        self.nparticles = np.sum(self.ketstates[:,0])
        self.h0Energies = [-Z*Z/2, -Z*Z/2, -Z*Z/8,\
                           -Z*Z/8, -Z*Z/18, -Z*Z/18]
        if self.nparticles == 2: 
            self.ground_state = [[0, 0], [0, 1]]
            self.a = [[0, 0], [1, 0], [1, 1], [2, 0], [2, 1]]
            self.i = [[0, 0], [0, 0], [0, 1], [0, 0], [0, 1]]
        elif self.nparticles == 4: 
            self.ground_state = [[0, 0], [0, 1], [1, 0], [1, 1]]
            self.a = [[0, 0], [2, 0], [2, 1], [2, 0], [2, 1]]
            self.i = [[0, 0], [0, 0], [0, 1], [1, 0], [1, 1]]
            
        else: 
            msg = 'States does not correspond to He or Be!'
            raise ValueError(msg)
        
        print(f"Number of particles: {self.nparticles}")
        
        print("States (ket) : ")
        print(self.ketstates)
        print("Single-particle energies: ") 
        print(self.h0Energies)
        print("V:") 
        print(self.V)
        print("First column of ket: ")
        print(self.ketstates[:, 0])
        
    def H0(self, p, q): 
        """
        <p|h_0|q>
        """
        if p==q: 
            energies = np.where(self.ketstates[:, p], \
                                self.h0Energies, 0.0)
            energy = np.sum(energies)
        else: 
            energy = 0.
        return energy
    
    
    def v(self, p, q, r, s): 
        """
        <pq|v|rs>
        """
        return self.V[p, q, r, s]
    
    def gs_H_ia(self, i, a):
        """
        Sum_k<ik||ak>
        """
        ni = i[0]; na = a[0]
        msi = i[1]; msa = a[1]
        energy = 0
        for k, spinstate in enumerate(self.ground_state): 
            if spinstate == i: 
                energy += 0 
            else: 
                energy += self.V[ni, spinstate[0], na, spinstate[0]]
        return energy
        
    def ai_H_jb(self, a, j, i, b): 
        """
        <aj||bi> + sum_{k\neq i\leq F}[<ak||bk>\delta{ij} 
        - <ik||ik>\delta{ab}] 
        + 0.5\sum_{kl\leqF}<kl||kl>\delta{ab}\delta{ij}
        """
        na = a[0]; nj=j[0]; nb=b[0]; ni=i[0]
        energy = 0 
        if a==b and i==j: 
            energy += self.H0(na*2, na*2)
            energy += self.V[na, ni, ni, na]
            for k, kstate in enumerate(self.ground_state): 
                if i==kstate: 
                    energy += 0
                else: 
                    energy += 0.5*self.V[na, kstate[0], na, kstate[0]]
                for l, lstate in enumerate(self.ground_state): 
                    if lstate == kstate or lstate == i: 
                        energy += 0
                    else: 
                        energy += 0.5*self.V[lstate[0], kstate[0], lstate[0], kstate[0]]
                    
            
        elif i==j: 
            energy += self.V[na, ni, ni, nb]
            for k, spinstate in enumerate(self.ground_state): 
                if i==spinstate: 
                    energy += 0 
                else: 
                    energy += 0.5*self.V[na, spinstate[0], nb, spinstate[0]]
                    
        elif a==b: 
            energy += self.V[na, nj, ni, na]
            for k, spinstate in enumerate(self.ground_state): 
                if i==spinstate or j==spinstate: 
                    energy += 0
                else: 
                    energy -= 0.5*self.V[nj, spinstate[0], ni, spinstate[0]]
                    
        else: 
            energy += self.V[na, ni, nj, nb]
        return energy 
    
    
        
    def ERef(self): 
        H0Energy = self.H0(0,0)
        vEnergy = 0
        for k, kstate in enumerate(self.ground_state): 
            for l, lstate in enumerate(self.ground_state):
                if kstate == lstate: 
                    vEnergy += 0
                else: 
                    nk = kstate[0]; nl = lstate[0]
                    vEnergy += 0.5*self.V[nk, nl, nk, nl]
                                          
        return H0Energy + vEnergy
    
    def calculate_Hmat(self): 
        Hmat = np.zeros((5, 5))
        a = self.a
        i = self.i
        Hmat[0, 0] = self.ERef()
        for k in range(1, 5): 
            Hmat[0, k] = self.gs_H_ia(i[k], a[k])
            Hmat[k, 0] = Hmat[0, k]
            
        for k in range(1, 5): 
            for l in range(1, 5): 
                Hmat[k, l] = self.ai_H_jb(a[k], i[l], i[k], a[l])
        return Hmat 


        

In [8]:
He = Hamiltonian(2, ketstates, VHe)
Hmat = He.calculate_Hmat()
print(Hmat)

Number of particles: 2
States (ket) : 
[[ True  True False  True False  True]
 [ True  True  True False  True False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]
Single-particle energies: 
[-2.0, -2.0, -0.5, -0.5, -0.2222222222222222, -0.2222222222222222]
V:
[[[[2.5        0.35742013 0.1758378 ]
   [0.35742013 0.0877915  0.04489167]
   [0.1758378  0.04489167 0.02307129]]

  [[0.35742013 0.83950617 0.20210591]
   [0.0877915  0.03432663 0.01817139]
   [0.04489167 0.0157438  0.00843616]]

  [[0.1758378  0.20210591 0.39794922]
   [0.04489167 0.01817139 0.00971541]
   [0.02307129 0.00843616 0.00452453]]]


 [[[0.35742013 0.0877915  0.04489167]
   [0.83950617 0.03432663 0.0157438 ]
   [0.20210591 0.01817139 0.00843616]]

  [[0.0877915  0.03432663 0.01817139]
   [0.03432663 0.6015625  0.08586823]
   [0.01817139 0.08586823 0.02990408]]

  [[0.04489167 0.01817139 0.00971541]
   [0.015

In [9]:
eigvals, eigvecs = np.linalg.eigh(Hmat)
print(eigvals)
print(eigvecs)

[-1.74750225 -1.0058527  -0.96418058 -0.59764183 -0.17008613]
[[-9.12978632e-01  1.16078952e-15 -1.37851646e-01 -8.31629649e-17
   3.84014246e-01]
 [ 2.77799623e-01  5.33767740e-01 -3.89634600e-01 -4.63780120e-01
   5.20588367e-01]
 [ 2.77799623e-01 -5.33767740e-01 -3.89634600e-01  4.63780120e-01
   5.20588367e-01]
 [ 7.78612739e-02 -4.63780120e-01  5.81965068e-01 -5.33767740e-01
   3.94023199e-01]
 [ 7.78612739e-02  4.63780120e-01  5.81965068e-01  5.33767740e-01
   3.94023199e-01]]


In [10]:
statesBe = np.zeros(shape=(6, 6), dtype=bool)
for i in range(6): 
    statesBe[i,i] = True
    statesBe[i, 0] = True; statesBe[i, 1] = True
    statesBe[i, 2] = True; statesBe[i, 3] = True
statesBe[4, 0] = False; statesBe[5, 1] = False; 
statesBe[2, 4] = True; statesBe[2, 2] = False; 
statesBe[3, 3] = False; statesBe[3, 5] = True; 
print(statesBe)

sp_energiesBe = np.zeros(6)
sp_energiesBe[0] = -8; sp_energiesBe[1] = -8; sp_energiesBe[2] = -2
sp_energiesBe[3] = -2; sp_energiesBe[4] = -8/9; sp_energiesBe[5] = -8/9

[[ True  True  True  True False False]
 [ True  True  True  True False False]
 [ True  True False  True  True False]
 [ True  True  True False False  True]
 [False  True  True  True  True False]
 [ True False  True  True False  True]]


In [11]:
Be = Hamiltonian(4, statesBe, VBe)

Number of particles: 4
States (ket) : 
[[ True  True  True  True False  True]
 [ True  True  True  True  True False]
 [ True  True False  True  True  True]
 [ True  True  True False  True  True]
 [False False  True False  True False]
 [False False False  True False  True]]
Single-particle energies: 
[-8.0, -8.0, -2.0, -2.0, -0.8888888888888888, -0.8888888888888888]
V:
[[[[2.5        0.35742013 0.1758378 ]
   [0.35742013 0.0877915  0.04489167]
   [0.1758378  0.04489167 0.02307129]]

  [[0.35742013 0.83950617 0.20210591]
   [0.0877915  0.03432663 0.01817139]
   [0.04489167 0.0157438  0.00843616]]

  [[0.1758378  0.20210591 0.39794922]
   [0.04489167 0.01817139 0.00971541]
   [0.02307129 0.00843616 0.00452453]]]


 [[[0.35742013 0.0877915  0.04489167]
   [0.83950617 0.03432663 0.0157438 ]
   [0.20210591 0.01817139 0.00843616]]

  [[0.0877915  0.03432663 0.01817139]
   [0.03432663 0.6015625  0.08586823]
   [0.01817139 0.08586823 0.02990408]]

  [[0.04489167 0.01817139 0.00971541]
   [0.015

In [12]:
HmatBe = Be.calculate_Hmat()
print(HmatBe)

[[-1.35404128e+01  2.07325405e-01  2.07325405e-01  4.90080041e-01
   4.90080041e-01]
 [ 2.07325405e-01 -7.96030629e+00  2.30712891e-02 -3.83310608e-01
   8.43615534e-03]
 [ 2.07325405e-01  2.30712891e-02 -7.96030629e+00  8.43615534e-03
  -3.83310608e-01]
 [ 4.90080041e-01 -3.83310608e-01  8.43615534e-03 -6.97350798e+00
   2.99040768e-02]
 [ 4.90080041e-01  8.43615534e-03 -3.83310608e-01  2.99040768e-02
  -6.97350798e+00]]


In [13]:
eigvals, eigvecs = np.linalg.eigh(HmatBe)
print(eigvals)

[-13.63166982  -8.12072937  -8.0199054   -6.86606028  -6.76967651]


In [457]:
class States: 
    def __init__(self, nbasis, nparticles, ex_deg, Z, Vmat):
        """
        Creates an instance of States, which 
        contains all states of our many-
        particle system (with preserved spin).
        
        Args: 
            nbasis int, 
                number of spinorbitals 
                in our single-particle 
                basis.
            nparticles int, 
                number of particles in 
                many-particle system. 
            ex_deg int, 
                number of maximum 
                excitations from ground
                state. 
        
        """
        self.V = Vmat 
        self.Z = Z
        self.nbasis = nbasis
        self.nparticles = nparticles
        self.ex_deg = ex_deg 
        self.SPenergies = self.single_particle_energies()
        self.ground_state = np.zeros(nbasis, dtype=bool)
        for i in range(self.nparticles): 
            self.ground_state[i] = True
        
        print("Initialized ground state: ")
        print(self.ground_state)
        print("\n")
        print(f"H0 ground state: {self.H0(self.ground_state)}")
        
        print("Single-particle energies: ")
        print(self.SPenergies)
        print("\n")
        
        # Possible hole states (all i)
        self.holes = np.zeros(shape=(self.nparticles, self.nbasis), dtype=bool)
        for i in range(self.nparticles): 
            self.holes[i,i] = True
    
        # Possible particle states (all a)
        self.particles = np.zeros(shape=(self.nbasis-self.nparticles, self.nbasis), dtype=bool)
        for i in range(self.nbasis-self.nparticles):
            self.particles[i, self.nparticles + i] = True   
        
        # Make set of all states 
        self.states = self.make_set_of_states()
        print("States to be used in energy calculations: ")
        print(self.states)
        print("\n")
        self.dimMat, nbasis = self.states.shape 
        # Check all states 
        print("Conservation of spin and particle for each row in states:")
        for i in range(self.dimMat): 
            print(self.check_spin(self.states[i, :])) 
        print("\n")
        print("Calucalte H[i,j]: ")
        print(self.calculate_Hij(0, 0))
        print("\n")
        
    def add_states(self, state1, state2): 
        """
        Makes the state that is the XOR
        evaluation between state1 and 
        state2. 
        """
        combined_state = state1^state2
        return combined_state 
        
    def check_spin(self, state): 
        """
        if i%2 = 1 spin up
        if i%2 = 0 spin down 
        
        Checks total spin in state
        """
        # first check number of particles: 
        if np.sum(state) != np.sum(self.ground_state): 
            print("The number of particles is not conserved.")
        
        indices = [i for i in range(self.nbasis) if state[i]]
        spin = 0 
        for index in indices: 
            if index%2: 
                spin += 1
            else: 
                spin -= 1
                
        return spin==0 
    
    def make_set_of_states(self): 
        ground_state = self.ground_state
        ex_deg = self.ex_deg
        states = [ground_state]
        num_excited, nbasis = self.particles.shape
        if num_excited > self.nparticles: 
            for i in range(num_excited): 
                ex_state = self.add_states(ground_state, self.particles[i, :])
                for j in range(self.nparticles): 
                    if j%2 == i%2: 
                        state = self.add_states(ex_state, self.holes[j, :])
                        states.append(state)
                        
        else: 
            for i in range(self.nparticles): 
                hole_state = self.add_states(ground_state, self.holes[i, :])
                for j in range(num_excited): 
                    if j%2 == i%2: 
                        state = self.add_states(hole_state, self.particles[j, :])
                        states.append(state)
    
        return np.array(states) 
    
    
    def single_particle_energies(self): 
        energies = []
        for i in range(self.nbasis): 
            n = i//2 + 1
            energy = -self.Z*self.Z/(2*n*n)
            energies.append(energy)
        return np.array(energies)
    
    def H0(self, state):
        """
        Onebody contribution 
        = <state|H0|state>
        """
        energies = np.where(state, self.SPenergies, 0)
        return np.sum(energies)
            
        
    def calculate_Hij(self, i, j): 
        """
        H[i,j] = <state[i]|H|state[j]>
        """
        energy = 0 
        if i == j: 
            energy += self.H0(self.states[i, :])
            print(energy)
            energy += self.elec_elec_interactions(i, i)
            print(energy)
            
        return energy 
    def elec_elec_interactions(self, i, j): 
        """
        state[i] = <e1|
        state[j] = |e2>
        """
        states = self.states
        energy = 0 
        
        hpi = self.add_states(self.ground_state, self.states[i, :])
        hpj = self.add_states(self.ground_state, self.states[j, :])
        shi = hpi[0] // 2
        spi = hpi[1] // 2
        shj = hpj[0] // 2
        spj = hpj[1] // 2
        
        if hpj[0]%2 == hpi[1]%2: 
            energy += self.V[spi, shj, shi, spj]
            energy -= self.V[spi, shj, spj, shi]
        else: 
            energy += self.V[spi, shj, shi, spj]
                            
        if i==0: 
            if j==0:
                indices = np.array([k for k in range(self.nbasis) if states[i,k]]) 
                sindices = indices // 2
                print(indices)
                
                for k in range(self.nparticles): 
                    for l in range(self.nparticles): 
                        if k==l: 
                            energy += 0 
                        if indices[k]%2 == indices[l]%2: 
                            energy += 0.5*self.V[sindices[k], sindices[l], sindices[k], sindices[l]] -\
                                      0.5*self.V[sindices[k], sindices[l], sindices[l], sindices[k]]
                        else: 
                            energy += 0.5*self.V[sindices[k], sindices[l], sindices[k], sindices[l]]
            else: 
                indices = np.array([k for k in range(self.nbasis) if states[j, k]])
                sindices = indices // 2
                hp = self.add_states(self.ground_state, states[j, :])
                hp_idx = np.array([k for k in range(self.nbasis) if hp[k]])
                s_h_idx = hp_idx[0] // 2 
                s_p_idx = hp_idx[1] // 2
                for j in range(self.nparticles): 
                    if hp_idx[0] == j: 
                        energy += 0 
                    elif hp_idx[0]%2 == j%2: 
                        energy += self.V[s_h_idx, j//2, j//2, s_p_idx]
                        energy -= self.V[s_h_idx, j//2, s_p_idx, j//2]
                    else: 
                        energy += self.V[s_h_idx, j//2, j//2, s_p_idx]
                        
                    
        elif i==j: 
            indices = np.array([k for k in range(self.nbasis) if states[i,k]]) 
            sindices = indices // 2
            print(indices)
            hp = self.add_states(self.ground_state, states[i, :])
            print(hp)
            hp_idx = np.array([k for k in range(self.nbasis) if holeparticle[k]])
            s_h_idx = hp_idx[0] // 2
            s_p_idx = hp_idx[1] // 2
            energy += V[s_particle_index, s_hole_index, s_hole_index, sindices[-1]] 
            energy -= V[sindices[-1], s_hole_index, sindices[-1], s_hole_index]
            for k in range(self.nparticles): 
                for l in range(self.nparticles): 
                    if k==l: 
                        energy += 0 
                    if indices[k]%2 == indices[l]%2: 
                        energy += 0.5*self.V[sindices[k], sindices[l], sindices[k], sindices[l]] -\
                                  0.5*self.V[sindices[k], sindices[l], sindices[l], sindices[k]]
                    else: 
                        energy += 0.5*self.V[sindices[k], sindices[l], sindices[k], sindices[l]]
        else: 
            hpi = self.add_states(self.ground_state, states[i, :])
            hpj = self.add_states(self.ground_state, states[j, :])
            energy += 0 
                    
        return energy 
    
    def e_e_int(self, i, j): 
        # hole-particle states i, j
        hpi = self.add_states(self.ground_state, self.states[i, :])
        hpj = self.add_states(self.ground_state, self.states[j, :])
        shi = hpi[0] // 2
        spi = hpi[1] // 2
        shj = hpj[0] // 2
        spj = hpj[1] // 2
        
        if hpj[0]%2 == hpi[1]%2: 
            energy += self.V[spi, shj, shi, spj]
            energy -= self.V[spi, shj, spj, shi]
        else: 
            energy += self.V[spi, shj, shi, spj]

        
        
print("Helium: \n\n")       
He = States(6, 2, 1, 2, VHe)
print("Beryllium :  ")
Be = States(6, 4, 1, 4, VBe)
        
        
        

Helium: 


Initialized ground state: 
[ True  True False False False False]


H0 ground state: -4.0
Single-particle energies: 
[-2.         -2.         -0.5        -0.5        -0.22222222 -0.22222222]


States to be used in energy calculations: 
[[ True  True False False False False]
 [False  True  True False False False]
 [ True False False  True False False]
 [False  True False False  True False]
 [ True False False False False  True]]


Conservation of spin and particle for each row in states:
True
True
True
True
True


Calucalte H[i,j]: 
-4.0
[0 1]
-1.5
-1.5


Beryllium :  
Initialized ground state: 
[ True  True  True  True False False]


H0 ground state: -20.0
Single-particle energies: 
[-8.         -8.         -2.         -2.         -0.88888889 -0.88888889]


States to be used in energy calculations: 
[[ True  True  True  True False False]
 [False  True  True  True  True False]
 [ True False  True  True False  True]
 [ True  True False  True  True False]
 [ True  True  True Fal

In [404]:
state1 = np.zeros(6, dtype=bool)
state2 = np.zeros(6, dtype=bool)
state1[0] = True; state1[1] = True; 
state2[0] = True; state2[3] = True; 

print(f"State 1: {state1}")
print(f"State 2: {state2}")

print(state1^state2)

State 1: [ True  True False False False False]
State 2: [ True False False  True False False]
[False  True False  True False False]


In [393]:
for i in range(5): 
    print(i%4)

0
1
2
3
0


In [458]:
-20 + VBe[0, 0, 0, 0] + 4*VBe[0, 1, 0, 1] - 2*VBe[0, 1, 1, 0] + VBe[1, 1, 1, 1]

-13.71599579903978